name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up musl gcc
        run: sudo apt-get install build-essential make musl-tools
      - name: Build
        run: CC=musl-gcc make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotenv
          path: dotenv
